/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CourseRegistration;

/**
 *
 * @author Nibir
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistrationJFrame extends javax.swing.JFrame {

    /**
     * 
     * Creates new form SaleApp
     */
    
    RegisterCourseController rcc;
    
    public RegistrationJFrame() {
        initComponents();
        rcc = new RegisterCourseController();  
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNewRegistration = new javax.swing.JButton();
        labelCourseID = new javax.swing.JLabel();
        textFieldCourseID = new javax.swing.JTextField();
        btnAddCourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registrationTable = new javax.swing.JTable();
        labelTotal = new javax.swing.JLabel();
        textFieldTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNewRegistration.setText("New Registration");
        btnNewRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRegistrationActionPerformed(evt);
            }
        });

        labelCourseID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCourseID.setText("Course ID:");

        textFieldCourseID.setName(""); // NOI18N

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        registrationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL #", "Course Title", "Credit", "Tution/Credit", "Sub Total", "Course ID"
            }
        ));
        jScrollPane1.setViewportView(registrationTable);

        labelTotal.setFont(new java.awt.Font("Tahoma", 1, 11));
        labelTotal.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelCourseID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCourse)
                    .addComponent(btnNewRegistration)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnNewRegistration)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCourseID))
                .addGap(18, 18, 18)
                .addComponent(btnAddCourse)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotal))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRegistrationActionPerformed
        // TODO add your handling code here:
        textFieldCourseID.setText("");
        textFieldTotal.setText("");
        
        DefaultTableModel model=(DefaultTableModel)registrationTable.getModel();
        int rc = model.getRowCount();
        for(int i = 0; i < rc; i++){
            model.removeRow(0);
        }
        
        rcc.makeNewRegistration();
    }//GEN-LAST:event_btnNewRegistrationActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
        if(!textFieldCourseID.getText().equals("")){
           try{
               if (textFieldCourseID.getText().equals("CSE 327")) {
                   String id = textFieldCourseID.getText();
                   rcc.addCourse(id);     
                   updateTable();
               }
               else if (textFieldCourseID.getText().equals("CSE 323")) {
                   String id = textFieldCourseID.getText();
                   rcc.addCourse(id);     
                   updateTable();
               } 
               else {
                   JOptionPane.showMessageDialog(null, "Enter Valid Course ID");
               }
           }catch(Exception ex){
               JOptionPane.showMessageDialog(null, "Enter Course ID");
               textFieldCourseID.setText("");
           }
       }else{
           JOptionPane.showMessageDialog(null, "You have to fill-up the form.");
       }
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void updateTable() {
        try{
            CourseFactory courseFactory = new CourseFactory();
            Course course = courseFactory.cList.get(rcc.registration.courseList.size()-1);
            
            Object[] row = { rcc.registration.courseList.size(), course.getTitle(),
                            course.getCredit(), course.getTuitionPerCredit(), 
                            course.getSubTotal(), course.getId()
                            };

            DefaultTableModel model = (DefaultTableModel) registrationTable.getModel();

            model.addRow(row);
            updateTotal();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Registration on specific course exceeds limit.");
        }
    }
    
    private void updateTotal() {
        textFieldTotal.setText(String.valueOf(rcc.registration.getTotal()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnNewRegistration;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCourseID;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable registrationTable;
    private javax.swing.JTextField textFieldCourseID;
    private javax.swing.JTextField textFieldTotal;
    // End of variables declaration//GEN-END:variables
}
